### ISSUE TITLE
Menu (Nav Drawer) UI

### ISSUE THREAD

**Issue by lyoung16** [dyzhu12/Beacon#2]
Mirror wireframe (screen 2)

**Comment by lyoung16** [comment]
![image](https://cloud.githubusercontent.com/assets/8762342/14894774/4eb0f00a-0d43-11e6-80d2-c588c320de11.png)

Current progress on Menu. Need to add actionListener to hamburger icon

**Comment by dyzhu12** [comment]
How come the nav drawer isn't coming from the home screen? If I look at the bottom right, it's pink fab with an email icon -- not the plus icon from the home screen. Is that just filler from android studio design view?
