### ISSUE TITLE
Home Screen Filter View, List View - UI

### ISSUE THREAD

**Issue by lyoung16** [dyzhu12/Beacon#5]
mirror wireframe (screen 16, 17)

**Comment by dyzhu12** [comment]
current progress with filter beacon -- implementing the clear filters button on the top right then will open pr

![image](https://cloud.githubusercontent.com/assets/7939025/15303208/8f7fc1de-1b84-11e6-8655-5ceb872e3226.png)

**Comment by dyzhu12** [comment]
![image](https://cloud.githubusercontent.com/assets/7939025/15303507/27cc18a6-1b86-11e6-891c-e74d55fe668c.png)
